/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarListings.view.MyPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel',

    requires: [
        'CarListings.view.MyPanelViewModel',
        'CarListings.view.MyPanelViewController',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.XTemplate',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar'
    ],

    controller: 'mypanel',
    viewModel: {
        type: 'mypanel'
    },
    frame: true,
    height: 622,
    width: 696,
    title: 'Car Listing',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'gridpanel',
            width: 396,
            title: '',
            store: 'CarDataStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'manufacturer',
                    text: 'Manufacturer'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'model',
                    text: 'Model'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'price',
                    text: 'Price'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'wiki',
                    text: 'Wiki'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'img',
                    text: 'Img'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'quality',
                    text: 'Quality'
                }
            ],
            listeners: {
                select: 'onGridpanelSelect'
            }
        },
        {
            xtype: 'panel',
            flex: 1,
            margins: '5 0 0 0',
            height: 147,
            itemId: 'detailPanel',
            tpl: [
                '`<img src="data/{img}" style="float: right" />',
                'Manufacturer: {manufacturer} ',
                'Model: <a href="{wiki}" target="_blank">{model}</a><br>',
                'Price: {price:usMoney}`'
            ]
        },
        {
            xtype: 'cartesian',
            height: 250,
            itemId: 'qualityChart',
            width: 400,
            insetPadding: 20,
            store: 'CarChartStore',
            axes: [
                {
                    type: 'category',
                    fields: [
                        'name'
                    ],
                    title: 'Quality',
                    position: 'bottom'
                },
                {
                    type: 'numeric',
                    fields: [
                        'rating'
                    ],
                    majorTickSteps: 10,
                    maximum: 5,
                    minimum: 0,
                    position: 'left',
                    title: 'Score'
                }
            ],
            series: [
                {
                    type: 'bar',
                    label: {
                        display: 'insideEnd',
                        field: 'rating',
                        color: '#333',
                        'text-anchor': 'middle'
                    },
                    xField: 'name',
                    yField: [
                        'rating'
                    ]
                }
            ]
        }
    ]

});